name: booking
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  font_awesome_flutter: ^10.5.0
  animated_splash_screen: ^1.3.0
  table_calendar: ^3.0.9
  equatable: ^2.0.0-nullsafety.3
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  connectivity: ^3.0.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  expandable: ^5.0.1
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.0
  jiffy: ^6.1.0
  image_picker: ^0.8.7+1
  http: ^0.13.0
  shared_preferences: ^2.2.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.2.2
  awesome_dialog: ^3.0.2
  dropdown_search: ^3.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter_native_splash:
  color: "#42a5f5"
  image: images/splash.png
  android_gravity: fill

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/
    - assets/icons/
